/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as CaregiverRouteImport } from './routes/caregiver'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UsersRouteImport } from './routes/users'
import { Route as AchievementsIndexRouteImport } from './routes/achievements/index'
import { Route as AiAssistantIndexRouteImport } from './routes/ai-assistant/index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics/index'
import { Route as AssessmentIndexRouteImport } from './routes/assessment/index'
import { Route as DailyChallengeIndexRouteImport } from './routes/daily-challenge/index'
import { Route as DailyPlanIndexRouteImport } from './routes/daily-plan/index'
import { Route as FamilyDashboardIndexRouteImport } from './routes/family-dashboard/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as GamesGameIdRouteImport } from './routes/games/$gameId'
import { Route as LearningIndexRouteImport } from './routes/learning/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverRoute = CaregiverRouteImport.update({
  id: '/caregiver',
  path: '/caregiver',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsIndexRoute = AchievementsIndexRouteImport.update({
  id: '/achievements/',
  path: '/achievements/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantIndexRoute = AiAssistantIndexRouteImport.update({
  id: '/ai-assistant/',
  path: '/ai-assistant/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIndexRoute = AssessmentIndexRouteImport.update({
  id: '/assessment/',
  path: '/assessment/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyChallengeIndexRoute = DailyChallengeIndexRouteImport.update({
  id: '/daily-challenge/',
  path: '/daily-challenge/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyPlanIndexRoute = DailyPlanIndexRouteImport.update({
  id: '/daily-plan/',
  path: '/daily-plan/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyDashboardIndexRoute = FamilyDashboardIndexRouteImport.update({
  id: '/family-dashboard/',
  path: '/family-dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningIndexRoute = LearningIndexRouteImport.update({
  id: '/learning/',
  path: '/learning/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/appointments': typeof AppointmentsRoute
  '/caregiver': typeof CaregiverRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/memories': typeof MemoriesRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/achievements/': typeof AchievementsIndexRoute
  '/ai-assistant/': typeof AiAssistantIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/assessment/': typeof AssessmentIndexRoute
  '/daily-challenge/': typeof DailyChallengeIndexRoute
  '/daily-plan/': typeof DailyPlanIndexRoute
  '/family-dashboard/': typeof FamilyDashboardIndexRoute
  '/games/': typeof GamesIndexRoute
  '/learning/': typeof LearningIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/appointments': typeof AppointmentsRoute
  '/caregiver': typeof CaregiverRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/memories': typeof MemoriesRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/achievements': typeof AchievementsIndexRoute
  '/ai-assistant': typeof AiAssistantIndexRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/assessment': typeof AssessmentIndexRoute
  '/daily-challenge': typeof DailyChallengeIndexRoute
  '/daily-plan': typeof DailyPlanIndexRoute
  '/family-dashboard': typeof FamilyDashboardIndexRoute
  '/games': typeof GamesIndexRoute
  '/learning': typeof LearningIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/resources': typeof ResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/appointments': typeof AppointmentsRoute
  '/caregiver': typeof CaregiverRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/memories': typeof MemoriesRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/achievements/': typeof AchievementsIndexRoute
  '/ai-assistant/': typeof AiAssistantIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/assessment/': typeof AssessmentIndexRoute
  '/daily-challenge/': typeof DailyChallengeIndexRoute
  '/daily-plan/': typeof DailyPlanIndexRoute
  '/family-dashboard/': typeof FamilyDashboardIndexRoute
  '/games/': typeof GamesIndexRoute
  '/learning/': typeof LearningIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/appointments'
    | '/caregiver'
    | '/help'
    | '/home'
    | '/login'
    | '/memories'
    | '/profile'
    | '/progress'
    | '/register'
    | '/reminders'
    | '/settings'
    | '/users'
    | '/games/$gameId'
    | '/achievements/'
    | '/ai-assistant/'
    | '/analytics/'
    | '/assessment/'
    | '/daily-challenge/'
    | '/daily-plan/'
    | '/family-dashboard/'
    | '/games/'
    | '/learning/'
    | '/notifications/'
    | '/reports/'
    | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/appointments'
    | '/caregiver'
    | '/help'
    | '/home'
    | '/login'
    | '/memories'
    | '/profile'
    | '/progress'
    | '/register'
    | '/reminders'
    | '/settings'
    | '/users'
    | '/games/$gameId'
    | '/achievements'
    | '/ai-assistant'
    | '/analytics'
    | '/assessment'
    | '/daily-challenge'
    | '/daily-plan'
    | '/family-dashboard'
    | '/games'
    | '/learning'
    | '/notifications'
    | '/reports'
    | '/resources'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/appointments'
    | '/caregiver'
    | '/help'
    | '/home'
    | '/login'
    | '/memories'
    | '/profile'
    | '/progress'
    | '/register'
    | '/reminders'
    | '/settings'
    | '/users'
    | '/games/$gameId'
    | '/achievements/'
    | '/ai-assistant/'
    | '/analytics/'
    | '/assessment/'
    | '/daily-challenge/'
    | '/daily-plan/'
    | '/family-dashboard/'
    | '/games/'
    | '/learning/'
    | '/notifications/'
    | '/reports/'
    | '/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AppointmentsRoute: typeof AppointmentsRoute
  CaregiverRoute: typeof CaregiverRoute
  HelpRoute: typeof HelpRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MemoriesRoute: typeof MemoriesRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  RegisterRoute: typeof RegisterRoute
  RemindersRoute: typeof RemindersRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  AchievementsIndexRoute: typeof AchievementsIndexRoute
  AiAssistantIndexRoute: typeof AiAssistantIndexRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  AssessmentIndexRoute: typeof AssessmentIndexRoute
  DailyChallengeIndexRoute: typeof DailyChallengeIndexRoute
  DailyPlanIndexRoute: typeof DailyPlanIndexRoute
  FamilyDashboardIndexRoute: typeof FamilyDashboardIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  LearningIndexRoute: typeof LearningIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver': {
      id: '/caregiver'
      path: '/caregiver'
      fullPath: '/caregiver'
      preLoaderRoute: typeof CaregiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements/': {
      id: '/achievements/'
      path: '/achievements'
      fullPath: '/achievements/'
      preLoaderRoute: typeof AchievementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant/': {
      id: '/ai-assistant/'
      path: '/ai-assistant'
      fullPath: '/ai-assistant/'
      preLoaderRoute: typeof AiAssistantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/': {
      id: '/assessment/'
      path: '/assessment'
      fullPath: '/assessment/'
      preLoaderRoute: typeof AssessmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-challenge/': {
      id: '/daily-challenge/'
      path: '/daily-challenge'
      fullPath: '/daily-challenge/'
      preLoaderRoute: typeof DailyChallengeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-plan/': {
      id: '/daily-plan/'
      path: '/daily-plan'
      fullPath: '/daily-plan/'
      preLoaderRoute: typeof DailyPlanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-dashboard/': {
      id: '/family-dashboard/'
      path: '/family-dashboard'
      fullPath: '/family-dashboard/'
      preLoaderRoute: typeof FamilyDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/': {
      id: '/learning/'
      path: '/learning'
      fullPath: '/learning/'
      preLoaderRoute: typeof LearningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AppointmentsRoute: AppointmentsRoute,
  CaregiverRoute: CaregiverRoute,
  HelpRoute: HelpRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MemoriesRoute: MemoriesRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  RegisterRoute: RegisterRoute,
  RemindersRoute: RemindersRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  AchievementsIndexRoute: AchievementsIndexRoute,
  AiAssistantIndexRoute: AiAssistantIndexRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  AssessmentIndexRoute: AssessmentIndexRoute,
  DailyChallengeIndexRoute: DailyChallengeIndexRoute,
  DailyPlanIndexRoute: DailyPlanIndexRoute,
  FamilyDashboardIndexRoute: FamilyDashboardIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  LearningIndexRoute: LearningIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
